### ISSUE TITLE
Checklist for My Favorite Books Project

### ISSUE THREAD

**Issue by omerjava** [lab-antwerp-1/group1-separate-of-concerns-project#1]
- [x] [repo](https://github.com/lab-antwerp-1/group1-separate-of-concerns-project) (with a complete README)
- [x] [live demo](https://lab-antwerp-1.github.io/group1-separate-of-concerns-project/)
- [/planning](https://github.com/lab-antwerp-1/group1-separate-of-concerns-project/tree/master/planning)
  - [ ] communication plan
  - [ ] constraints
  - [x] backlog
  - [ ] wireframe
  - [ ] development strategy
  - [ ] retrospective
- [x] [project board](https://github.com/lab-antwerp-1/group1-separate-of-concerns-project/projects)
